service: ${file(config.json):SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:*"
          Resource: ${file(config.json):SENDER_ARN}

functions:
  receive:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: post
          request:
            parameters:
              querystrings:
                format: true
